[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
counter = "0.5.2"
indoc = "1.0"
itertools = "0.10.3"
pathfinding = "4.11.0"
petgraph = "0.6.5"
regex = "1"
smart-default = "0.6.0"